2025-02-17 01:51:34,365 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='quests-usage-dev.prod.zettablock.com', port=443): Read timed out. (read timeout=10)")': /api/user/0x6646de28934127ba20ea5444206cfd1c382a7c17/stats
2025-02-17 01:51:47,209 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='quests-usage-dev.prod.zettablock.com', port=443): Read timed out. (read timeout=10)")': /api/user/0x6646de28934127ba20ea5444206cfd1c382a7c17/stats
2025-02-17 01:52:02,118 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='quests-usage-dev.prod.zettablock.com', port=443): Read timed out. (read timeout=10)")': /api/user/0x6646de28934127ba20ea5444206cfd1c382a7c17/stats
2025-02-17 01:52:12,872 - ERROR - Error checking points status: HTTPSConnectionPool(host='quests-usage-dev.prod.zettablock.com', port=443): Max retries exceeded with url: /api/user/0x6646de28934127ba20ea5444206cfd1c382a7c17/stats (Caused by ReadTimeoutError("HTTPSConnectionPool(host='quests-usage-dev.prod.zettablock.com', port=443): Read timed out. (read timeout=10)"))
2025-02-17 01:52:55,642 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='quests-usage-dev.prod.zettablock.com', port=443): Read timed out. (read timeout=10)")': /api/user/0x6646de28934127ba20ea5444206cfd1c382a7c17/stats
2025-02-17 01:53:08,546 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='quests-usage-dev.prod.zettablock.com', port=443): Read timed out. (read timeout=10)")': /api/user/0x6646de28934127ba20ea5444206cfd1c382a7c17/stats
2025-02-17 01:53:23,313 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='quests-usage-dev.prod.zettablock.com', port=443): Read timed out. (read timeout=10)")': /api/user/0x6646de28934127ba20ea5444206cfd1c382a7c17/stats
2025-02-17 01:53:34,094 - ERROR - Error checking points status: HTTPSConnectionPool(host='quests-usage-dev.prod.zettablock.com', port=443): Max retries exceeded with url: /api/user/0x6646de28934127ba20ea5444206cfd1c382a7c17/stats (Caused by ReadTimeoutError("HTTPSConnectionPool(host='quests-usage-dev.prod.zettablock.com', port=443): Read timed out. (read timeout=10)"))
2025-02-17 01:54:38,281 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='quests-usage-dev.prod.zettablock.com', port=443): Read timed out. (read timeout=10)")': /api/user/0x6646de28934127ba20ea5444206cfd1c382a7c17/stats
2025-02-17 01:54:51,177 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='quests-usage-dev.prod.zettablock.com', port=443): Read timed out. (read timeout=10)")': /api/user/0x6646de28934127ba20ea5444206cfd1c382a7c17/stats
2025-02-17 01:55:06,098 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='quests-usage-dev.prod.zettablock.com', port=443): Read timed out. (read timeout=10)")': /api/user/0x6646de28934127ba20ea5444206cfd1c382a7c17/stats
2025-02-17 01:55:16,872 - ERROR - Error checking points status: HTTPSConnectionPool(host='quests-usage-dev.prod.zettablock.com', port=443): Max retries exceeded with url: /api/user/0x6646de28934127ba20ea5444206cfd1c382a7c17/stats (Caused by ReadTimeoutError("HTTPSConnectionPool(host='quests-usage-dev.prod.zettablock.com', port=443): Read timed out. (read timeout=10)"))
2025-02-17 01:56:26,055 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='quests-usage-dev.prod.zettablock.com', port=443): Read timed out. (read timeout=10)")': /api/user/0x6646de28934127ba20ea5444206cfd1c382a7c17/stats
2025-02-17 01:56:38,840 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='quests-usage-dev.prod.zettablock.com', port=443): Read timed out. (read timeout=10)")': /api/user/0x6646de28934127ba20ea5444206cfd1c382a7c17/stats
2025-02-17 01:56:53,603 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='quests-usage-dev.prod.zettablock.com', port=443): Read timed out. (read timeout=10)")': /api/user/0x6646de28934127ba20ea5444206cfd1c382a7c17/stats
