2025-02-17 00:38:41,637 - WARNING - [connectionpool.py:870] - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='quests-usage-dev.prod.zettablock.com', port=443): Read timed out. (read timeout=10)")': /health
2025-02-17 00:38:54,362 - WARNING - [connectionpool.py:870] - Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='quests-usage-dev.prod.zettablock.com', port=443): Read timed out. (read timeout=10)")': /health
2025-02-17 00:39:09,122 - WARNING - [connectionpool.py:870] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='quests-usage-dev.prod.zettablock.com', port=443): Read timed out. (read timeout=10)")': /health
2025-02-17 00:39:19,883 - INFO - [main.py:687] - Received shutdown signal, cleaning up...
