2025-02-17 01:22:30,601 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='quests-usage-dev.prod.zettablock.com', port=443): Read timed out. (read timeout=10)")': /api/user/0x6646de28934127ba20ea5444206cfd1c382a7c17/stats
2025-02-17 01:22:43,327 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='quests-usage-dev.prod.zettablock.com', port=443): Read timed out. (read timeout=10)")': /api/user/0x6646de28934127ba20ea5444206cfd1c382a7c17/stats
2025-02-17 01:22:58,119 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='quests-usage-dev.prod.zettablock.com', port=443): Read timed out. (read timeout=10)")': /api/user/0x6646de28934127ba20ea5444206cfd1c382a7c17/stats
2025-02-17 01:23:08,907 - ERROR - Error checking points status: HTTPSConnectionPool(host='quests-usage-dev.prod.zettablock.com', port=443): Max retries exceeded with url: /api/user/0x6646de28934127ba20ea5444206cfd1c382a7c17/stats (Caused by ReadTimeoutError("HTTPSConnectionPool(host='quests-usage-dev.prod.zettablock.com', port=443): Read timed out. (read timeout=10)"))
2025-02-17 01:23:59,722 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='quests-usage-dev.prod.zettablock.com', port=443): Read timed out. (read timeout=10)")': /api/user/0x6646de28934127ba20ea5444206cfd1c382a7c17/stats
2025-02-17 01:24:12,619 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='quests-usage-dev.prod.zettablock.com', port=443): Read timed out. (read timeout=10)")': /api/user/0x6646de28934127ba20ea5444206cfd1c382a7c17/stats
2025-02-17 01:24:27,399 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='quests-usage-dev.prod.zettablock.com', port=443): Read timed out. (read timeout=10)")': /api/user/0x6646de28934127ba20ea5444206cfd1c382a7c17/stats
2025-02-17 01:24:38,304 - ERROR - Error checking points status: HTTPSConnectionPool(host='quests-usage-dev.prod.zettablock.com', port=443): Max retries exceeded with url: /api/user/0x6646de28934127ba20ea5444206cfd1c382a7c17/stats (Caused by ReadTimeoutError("HTTPSConnectionPool(host='quests-usage-dev.prod.zettablock.com', port=443): Read timed out. (read timeout=10)"))
2025-02-17 01:25:11,759 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='quests-usage-dev.prod.zettablock.com', port=443): Read timed out. (read timeout=10)")': /api/user/0x6646de28934127ba20ea5444206cfd1c382a7c17/stats
2025-02-17 01:25:24,552 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='quests-usage-dev.prod.zettablock.com', port=443): Read timed out. (read timeout=10)")': /api/user/0x6646de28934127ba20ea5444206cfd1c382a7c17/stats
2025-02-17 01:25:39,453 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='quests-usage-dev.prod.zettablock.com', port=443): Read timed out. (read timeout=10)")': /api/user/0x6646de28934127ba20ea5444206cfd1c382a7c17/stats
